version: '2.1'
services:
  server:
    environment:
      - WS_URL=ws://host.docker.internal:8001
      - SENDING_INTERVAL_MS=10000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    container_name: mock-server
    restart: always
