version: '2.1'
services:
  server:
    environment:
      - WS_URL=ws://host.docker.internal:8001
    build: .
    ports:
      - 9000:9000
    container_name: mock-server
    restart: always
